### PR TITLE
Fixing deprecations and speed up

### PR DESCRIPTION
**Pull request by MetricMike**
Thank you so much for creating this wrapper. While working with this, I took a pass at upgrading some of the outdated libraries.

Old test suite ~40 seconds.
New test suite ~20 seconds.

### CODE REVIEW

**Comment by tyrauber** [comment]
Thanks for the contribution, @MetricMike. I appreciate you updating the libraries and specs.  Where exactly are the breaking changes? The result is the same?  Why the necessity to bump to v2.0.1?

**Comment by MetricMike** [comment]
Overly aggressive versioning on my part.

Technically, httprb doesn't support Ruby < 2, so that could break for older apps relying on census_api. Running specs on 1.9.3 seems to work fine though, so I dropped the version down to 1.1.0

**Comment by tyrauber** [comment]
You also added the rvm files to .gitignore, perfect.  Just remove the updated authorship and this is good to go.  If you are interested in being an author of this gem and helping with the development and  maintenance going forward, shoot me an email and we can discuss adding you as a contributor.  Thanks again for the update.  Solid PR.

**Comment by MetricMike** [comment]
If I end up doing more work on it, will definitely shoot you an email, but
for now I took my name off.

You're my first public PR so thanks for being so helpful during the process
=)

**Comment by tyrauber** [comment]
Not a problem. Great work!  Most appreciated. Merged and pushed [v1.1.0](https://rubygems.org/gems/census_api/versions/1.1.0).

**Pull request merged**
